# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    raddit_app.site_name: Raddit

services:
    raddit_app.form.registration_type:
        class: Raddit\AppBundle\Form\RegistrationType
        arguments: ["@security.password_encoder"]
        tags:
            - { name: form.type }

    raddit_app.twig.app_extension:
        class: Raddit\AppBundle\Twig\AppExtension
        calls:
            - [setSiteName, ["%raddit_app.site_name%"]]
        tags:
            - { name: twig.extension }
